name: Publish Container Image Rootless

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Tracing
        run: |
        echo "pwd"
        pwd
        echo "ls"
        ls
        echo "ls -l"
        ls

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ashishkurmi/actions-runner-dind-rootless:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: DockerfileOutpost
